apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-job
spec:
  schedule: "* * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo-job
              image: demo-k8s-cronjob
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure