apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-job
spec:
  schedule: "*/5 * * * *" #	Run every 5 minute. https://crontab.cronhub.io/
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo-job
              image: demo-k8s-cronjob
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure